# Generated by Django 5.1.2 on 2024-11-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('price', models.CharField(default=0, max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
