# Generated by Django 5.1.2 on 2024-11-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclelist', '0002_vehiclecategory_vehiclelocation_vehicle_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelocation',
            name='location',
            field=models.CharField(choices=[('ATL', 'Hartsfield–Jackson Atlanta International Airport (ATL)'), ('LAX', 'Los Angeles International Airport (LAX)'), ('ORD', "O'Hare International Airport (ORD)"), ('DFW', 'Dallas/Fort Worth International Airport (DFW)'), ('DEN', 'Denver International Airport (DEN)'), ('JFK', 'John F. Kennedy International Airport (JFK)'), ('SFO', 'San Francisco International Airport (SFO)'), ('SEA', 'Seattle-Tacoma International Airport (SEA)'), ('LAS', 'McCarran International Airport (LAS)'), ('MCO', 'Orlando International Airport (MCO)'), ('MIA', 'Miami International Airport (MIA)'), ('CLT', 'Charlotte Douglas International Airport (CLT)'), ('PHX', 'Phoenix Sky Harbor International Airport (PHX)'), ('IAH', 'George Bush Intercontinental Airport (IAH)'), ('BOS', 'Boston Logan International Airport (BOS)'), ('EWR', 'Newark Liberty International Airport (EWR)'), ('IAD', 'Washington Dulles International Airport (IAD)'), ('PHL', 'Philadelphia International Airport (PHL)'), ('MSP', 'Minneapolis–Saint Paul International Airport (MSP)'), ('DTW', 'Detroit Metropolitan Airport (DTW)'), ('FLL', 'Fort Lauderdale–Hollywood International Airport (FLL)'), ('SLC', 'Salt Lake City International Airport (SLC)'), ('AUS', 'Austin-Bergstrom International Airport (AUS)'), ('SAN', 'San Diego International Airport (SAN)'), ('TPA', 'Tampa International Airport (TPA)'), ('PDX', 'Portland International Airport (PDX)'), ('HNL', 'Honolulu International Airport (HNL)')], max_length=150),
        ),
    ]
