# Generated by Django 5.1.2 on 2024-11-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclelist', '0003_alter_vehiclelocation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='imagefield',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
