# Generated by Django 5.1.2 on 2024-11-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclelist', '0005_vehicle_free_cancellation_vehicle_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True),
        ),
    ]
